// -----------------------------------------------------------------------------
// Start bottom - taint analysis rules
// -----------------------------------------------------------------------------

/**
 * Bottom Method 中需要强制设置的污点源 
*/
.decl Bottom_Method_Forced_Source_Value(value: symbol, method: Method)

Bottom_Method_Forced_Source_Value(value, method) :-
	BottomMethod(method),
	TaintSourceVariable(var, method),
	mainAnalysis.VarPointsTo(_, value, method, var).

MICRO_CUSTOM_TAINT(source, value, method, label) :-
	source = method,
	label = method,
	Bottom_Method_Forced_Source_Value(value, method).

// 处理 field
MICRO_CUSTOM_TAINT(source, value, in_method, label):-
	Extension_Value(_, field_value, _, in_method, _, _), 
	source = in_method,
	value = field_value,
	label = in_method,
	BottomMethod(in_method).

// 处理 array
MICRO_CUSTOM_TAINT(source, value, in_method, label):-
	AssignHeapAllocation(value, base, in_method),
	StoreArrayIndex(_, base, in_method),
	source = in_method,
	label = in_method,
	BottomMethod(in_method).
// -----------------------------------------------------------------------------
// End bottom - taint analysis rules
// -----------------------------------------------------------------------------