// -----------------------------------------------------------------------------
// Start bottom - taint analysis rules
// -----------------------------------------------------------------------------

/**
 * Bottom Method 中需要强制设置的污点源 
*/
.decl Bottom_Method_Forced_Source_Value(value: symbol, method: Method)
.output Bottom_Method_Forced_Source_Value
.printsize Bottom_Method_Forced_Source_Value

Bottom_Method_Forced_Source_Value(value, method) :-
	BottomMethod(method),
	TaintSourceVariable(var, method),
	mainAnalysis.VarPointsTo(_, value, method, var).

Bottom_Method_Forced_Source_Value(value, method) :-
	Extension_Value(_, value, _, _, _, method).

MICRO_CUSTOM_TAINT(source, value, method, label) :-
	source = method,
	label = method,
	Bottom_Method_Forced_Source_Value(value, method).


// -----------------------------------------------------------------------------
// End bottom - taint analysis rules
// -----------------------------------------------------------------------------