// -----------------------------------------------------------------------------
// start Node - VarPointsTo analysis rules
// -----------------------------------------------------------------------------

.decl NodeMethod(method: Method)
.printsize NodeMethod
.output NodeMethod

NodeMethod(method) :-
	isMethod(method),
	ImMethod_WithInvocation(method).

/**
 * 通过 ForcedReachable 强制产生, 上下文为 BottomMethod 的 指针信息
 * 指针信息：包括，形式参数 和 this 指针
 * 潜在问题，field 和 数组 上的指针信息可能会丢失
*/
mainAnalysis.ForcedReachable(method) :-
	NodeMethod(method).

Target_Lost_Store_Target(base, signature, in_method, to) :-
	LoadInstanceField(base, signature, to, in_method),
	!StoreInstanceField(_, base, signature, in_method),
	NodeMethod(in_method).

// -----------------------------------------------------------------------------
// End Node - VarPointsTo analysis rules
// -----------------------------------------------------------------------------