// 加载自定义宏
#include "micro.dl"
// -----------------------------------------------------------------------------
// Start Summary Analysis rules
// -----------------------------------------------------------------------------

// 基本组件: 根据method中的传播情况，实时增量新的传播摘要信息
#include "utils/MethodSummarizer.dl"

// // 基本组件: 
// #include "utils/Support-Reflect.dl"
// #include "utils/Support-Proxy.dl"

#include "utils/debug.dl"

// Step 1 : 列出所有的函数
#include "utils/List-Targets.dl"

// Step 2 : 计算 Bottom 中的 指针分析 和 污点分析 (摘要)
#include "utils/Bottom-VarPointsTo-analysis.dl"
#include "utils/Bottom-TaintTransfer-analysis.dl"

// Step 2 : 计算 Node 中的 指针分析 和 污点分析 (摘要)
#include "utils/Node-VarPointsTo-analysis.dl"
#include "utils/Node-TaintTransfer-analysis.dl"

#include "utils/AnalysisResult.dl"


// -----------------------------------------------------------------------------
// End Summary Analysis rules
// -----------------------------------------------------------------------------